version: '2.4'

services:
    php:
        build:
            context: ./dockers/php7-fpm/
        env_file:
            ./.env
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www/current

    nginx:
        build:
            context: ./dockers/nginx/
        ports:
            - '80:80'
        volumes_from:
            - php

    sqlserver:
        image: mysql:5.7.22
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - '3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: ${DATABASE_HOST}
            PMA_PORT: ${DATABASE_PORT}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - '3300:80'
        links:
            - sqlserver:data
        depends_on:
            - sqlserver

    build:
        build:
            context: ./dockers/build
        volumes_from:
            - php
        tty: true

    maildev:
        image: djfarrelly/maildev
        ports:
            - "1080:80"
            - "25"